# Support Dedekind development

github: [Engineer1080]
# patreon: # Replace with your Patreon username
# ko_fi: # Replace with your Ko-fi username
# open_collective: # Replace with your Open Collective username
# custom: ['https://your-custom-donation-link.com']
